apiVersion: v1
kind: Service
metadata:
  name: nacos-hs
  namespace: nacos
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - port: 8848
      targetPort: 8848
      protocol: TCP
      name: http
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
      protocol: TCP
  selector:
    app: nacos
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-cs
  namespace: nacos
spec:
  type: ClusterIP
  ports:
    - port: 8848
      targetPort: 8848
      protocol: TCP
      name: http
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
      protocol: TCP
  selector:
    app: nacos

