apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: statefulSet.yaml
    target:
      kind: StatefulSet
      name: nacos
      namespace: nacos
  - path: cm.yaml
    target:
      kind: ConfigMap
      name: nacos
      namespace: nacos