apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nacos
resources:
  - ../../base
  - cm.yaml
patches:
  - path: statefulset.yaml
    target:
      kind: StatefulSet
      name: nacos
