apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nacos
resources:
  - ../../base
patches:
  - path: cm.yaml
    target:
      kind: ConfigMap
      name: nacos-cm
      namespace: nacos
