apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: nacos
  labels:
    app: nacos
spec:
  serviceName: nacos-hs
  replicas: 3
  selector:
    matchLabels:
      app: nacos
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
